services:
  kostal-collector:
    image: ghcr.io/patricknitsch/kostal-collector:latest
    restart: unless-stopped
    environment:
      KOSTAL_HOST:
      KOSTAL_PROTOCOL:
      KOSTAL_PORT:
      KOSTAL_INTERVAL:
      OUTPUT_TARGET: influxdb
      INFLUX_BUCKET:
      INFLUX_HOST: influxdb
      INFLUX_MEASUREMENT_KOSTAL:
      INFLUX_ORG:
      INFLUX_TOKEN: ${INFLUX_TOKEN_WRITE}
      MQTT_HOST:
      MQTT_PORT: 1883
      MQTT_USERNAME:
      MQTT_PASSWORD:
      MQTT_TOPIC_PREFIX: kostal
      MQTT_RETAIN: "false"
      KOSTAL_METRICS: "33556736:dc_input_power:float,67109120:ac_output_power:float,16780032:status:integer"

networks:
  default:
    name: solectrus_default
